### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by SlimeQ** [CodeMySky/java-importer#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 12.04.5
**Thrown From**: [java-importer](https://github.com/CodeMySky/java-importer) package, v1.3.2
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/quincy/.atom/packages/java-importer/lib/java-importer.coffee:53

TypeError: undefined is not a function
  at PathSearcher.<anonymous> (/home/quincy/.atom/packages/java-importer/lib/java-importer.coffee:53:41)
  at emitOne (events.js:77:13)
  at PathSearcher.emit (events.js:166:7)
  at ChunkedLineReader.<anonymous> (/home/quincy/.atom/packages/java-importer/node_modules/scandal/lib/path-searcher.js:86:17)
  at emitNone (events.js:67:13)
  at ChunkedLineReader.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -9:52.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -9:44.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:43 core:save (atom-text-editor.editor.is-focused)
     -9:00.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -9:00.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -9:00.3.0 editor:indent (atom-text-editor.editor.is-focused)
  9x -8:52.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -7:18.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -6:58.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:40.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
java-importer, v1.3.2
language-ejs, v0.2.0
language-gradle, v0.0.3
project-manager, v1.15.11
remote-edit, v1.8.13
set-syntax, v0.3.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by CodeMySky** [comment]
Hi @SlimeQ ,
    Thank you very much for using my package! I really appreciate it.
    I have just patched the package. Can you upgrade and help test it again?

Sean

**Comment by SlimeQ** [comment]
oh wow, thanks for responding so quickly! i did a full atom upgrade and updated the package and it mostly works now, probably because of your update. however i'm still having problems importing anything in a list declaration. for example

```
List<ForeignObj>
```

causes problems on both List and ForeignObj because the the plugin receives the strings "List<" and "ForeignObj>". it's easy to work around by just adding a space to the end of the class name, but still probably a bug.

thank you so much for writing/maintaining this, you've made my work environment bearable! :)

**Comment by CodeMySky** [comment]
Hi @SlimeQ , I have released v1.3.5 of java-importer, can you help test if the word selection issue still exists?

Sean

**Comment by SlimeQ** [comment]
i still have the word selection issue. i'm also noticing that it pulls in String[] rather than String (that syntax is from APEX, but the plugin should work regardless)

i've also had some problems finding local imports. my directory structure is such that there are multiple folders within my main package, so i suspect that may have something to do with it. this may warrant a second issue though

**Comment by CodeMySky** [comment]
I have separated those two bugs. Closing this now
