### ISSUE TITLE
Java-Importer can not extract right class name

### ISSUE THREAD

**Issue by CodeMySky** [CodeMySky/java-importer#2]
According to https://github.com/CodeMySky/java-importer/issues/1
Java-Importer seems to have some problem extracting the right class name.
I have already fixed situation like `List<ForeignObj>`
But there are still some other issue like `String[]` can not be extracted correctly.

**Comment by CodeMySky** [comment]
I'm adding more test case to it. Please comment to add more test cases.

**Comment by CodeMySky** [comment]
![testsquarebracket](https://cloud.githubusercontent.com/assets/1545856/8921945/86d63098-34aa-11e5-8454-2aa0d466af51.gif)
It seems that String[] is working well. Is that right? @SlimeQ

**Comment by SlimeQ** [comment]
yeah, i'm seeing that it's working now for me too... unsure why that happened. will take better notes if it happens again.

**Comment by CodeMySky** [comment]
Closing this for now. Until other similar issues are found.
